/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/gen_mp_real_small_tables.py -- do not edit */

#ifndef MP_REAL_SMALL_TABLES_H
#define MP_REAL_SMALL_TABLES_H

#include "flint.h"

#if FLINT_BITS == 64

/* exp(j/2^7), j < 128 (3 fraction limbs, integral limb); 4 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_exp_e1[512];
/* exp(j/2^14) - 1, j < 128; 3 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_exp_e2[384];
/* exp(j/2^21) - 1, j < 128; 3 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_exp_e3[384];
/* log1p level 1: D[j] = floor(2^23 j / (2^7 + j)) / 2^23, j < 128 (one limb); 1 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_log_d1[128];
/* log1p level 1: -log(1 - D[j]), j < 128; 3 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_log_l1[384];
/* log1p level 2: D[j] = floor(2^30 j / (2^14 + j)) / 2^30, j < 129 (one limb); 1 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_log_d2[129];
/* log1p level 2: -log(1 - D[j]), j < 129; 3 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_log_l2[387];
/* log1p level 3: D[j] = floor(2^37 j / (2^21 + j)) / 2^37, j < 129 (one limb); 1 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_log_d3[129];
/* log1p level 3: -log(1 - D[j]), j < 129; 3 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_log_l3[387];
/* log1p level 4: D[j] = floor(2^44 j / (2^28 + j)) / 2^44, j < 129 (one limb); 1 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_log_d4[129];
/* log1p level 4: -log(1 - D[j]), j < 129; 3 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_log_l4[387];
/* sin(j/2^7), 1 - cos(j/2^7), j < 128 (3 + 3 fraction limbs); 6 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_sin_cos_s1[768];
/* sin(j/2^14), 1 - cos(j/2^14), j < 128 (3 + 3 fraction limbs); 6 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_sin_cos_s2[768];
/* atan(j/2^9), j < 512; 3 limbs per entry */
FLINT_DLL extern const ulong _mp_real_small_atan_a[1536];

#endif

#endif
