/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/*
    Generated by src/machine_vectors/test/t-force_generic.c's generation
    recipe (see the comment there); do not edit by hand.

    Object like macros renaming every identifier defined by
    machine_vectors_generic.h, so that t-force_generic.c can instantiate
    the generic backend a second (and third) time in a translation unit
    whose primary backend was already chosen by machine_vectors.h. Since
    most of the definitions in machine_vectors_generic.h paste the final
    identifiers together from macro arguments, the renaming must map the
    final names, which is why this list is generated from preprocessed
    output rather than from the header text.

    Usage: define exactly one of FLINT_MV_RENAME_MVG (rename to mvg_*),
    FLINT_MV_RENAME_MVS (rename to mvs_*) or FLINT_MV_RENAME_UNDEF
    (remove the renames) and include this file; the guard macro is
    consumed. This file intentionally has no include guard.
*/

#if defined(FLINT_MV_RENAME_MVG)
#undef FLINT_MV_RENAME_MVG
#define _vec2d_i64 mvg__vec2d_i64
#define _vec2d_round_i64 mvg__vec2d_round_i64
#define _vec2i mvg__vec2i
#define _vec2n_small_i64_d mvg__vec2n_small_i64_d
#define _vec2u mvg__vec2u
#define _vec2d_fma mvg__vec2d_fma
#define _vec4d_fma mvg__vec4d_fma
#define _vec2d_signmask mvg__vec2d_signmask
#define _vec4d_signmask mvg__vec4d_signmask
#define _vec4d_i64 mvg__vec4d_i64
#define _vec4d_round_i64 mvg__vec4d_round_i64
#define _vec4i mvg__vec4i
#define _vec4n_small_i64_d mvg__vec4n_small_i64_d
#define _vec4u mvg__vec4u
#define _vec_generic_blendv1 mvg__vec_generic_blendv1
#define _vec_generic_i64_51_get_d mvg__vec_generic_i64_51_get_d
#define _vec_generic_mulmod1 mvg__vec_generic_mulmod1
#define _vec_generic_nmulmod1 mvg__vec_generic_nmulmod1
#define _vec_generic_reduce_pm1n_to_pmhn1 mvg__vec_generic_reduce_pm1n_to_pmhn1
#define _vec_generic_reduce_to_pm1n1 mvg__vec_generic_reduce_to_pm1n1
#define _vec_generic_round_i64_52 mvg__vec_generic_round_i64_52
#define vec16f mvg_vec16f
#define vec16f_add mvg_vec16f_add
#define vec16f_floor mvg_vec16f_floor
#define vec16f_fmadd mvg_vec16f_fmadd
#define vec16f_fnmadd mvg_vec16f_fnmadd
#define vec16f_load mvg_vec16f_load
#define vec16f_load_aligned mvg_vec16f_load_aligned
#define vec16f_load_unaligned mvg_vec16f_load_unaligned
#define vec16f_mul mvg_vec16f_mul
#define vec16f_set_f mvg_vec16f_set_f
#define vec16f_store mvg_vec16f_store
#define vec16f_store_aligned mvg_vec16f_store_aligned
#define vec16f_store_unaligned mvg_vec16f_store_unaligned
#define vec16f_sub mvg_vec16f_sub
#define vec16f_zero mvg_vec16f_zero
#define vec1d mvg_vec1d
#define vec1d_abs mvg_vec1d_abs
#define vec1d_add mvg_vec1d_add
#define vec1d_addsub mvg_vec1d_addsub
#define vec1d_blendv mvg_vec1d_blendv
#define vec1d_convert_limited_vec1n mvg_vec1d_convert_limited_vec1n
#define vec1d_div mvg_vec1d_div
#define vec1d_floor mvg_vec1d_floor
#define vec1d_fmadd mvg_vec1d_fmadd
#define vec1d_fmsub mvg_vec1d_fmsub
#define vec1d_fnmadd mvg_vec1d_fnmadd
#define vec1d_fnmsub mvg_vec1d_fnmsub
#define vec1d_half mvg_vec1d_half
#define vec1d_load mvg_vec1d_load
#define vec1d_load_aligned mvg_vec1d_load_aligned
#define vec1d_load_unaligned mvg_vec1d_load_unaligned
#define vec1d_max mvg_vec1d_max
#define vec1d_min mvg_vec1d_min
#define vec1d_mul mvg_vec1d_mul
#define vec1d_mulmod mvg_vec1d_mulmod
#define vec1d_neg mvg_vec1d_neg
#define vec1d_nmulmod mvg_vec1d_nmulmod
#define vec1d_one mvg_vec1d_one
#define vec1d_reduce_0n_to_pmhn mvg_vec1d_reduce_0n_to_pmhn
#define vec1d_reduce_2n_to_n mvg_vec1d_reduce_2n_to_n
#define vec1d_reduce_pm1n_to_pmhn mvg_vec1d_reduce_pm1n_to_pmhn
#define vec1d_reduce_pm1no_to_0n mvg_vec1d_reduce_pm1no_to_0n
#define vec1d_reduce_to_0n mvg_vec1d_reduce_to_0n
#define vec1d_reduce_to_pm1n mvg_vec1d_reduce_to_pm1n
#define vec1d_reduce_to_pm1no mvg_vec1d_reduce_to_pm1no
#define vec1d_round mvg_vec1d_round
#define vec1d_same mvg_vec1d_same
#define vec1d_same_mod mvg_vec1d_same_mod
#define vec1d_set_d mvg_vec1d_set_d
#define vec1d_store mvg_vec1d_store
#define vec1d_store_aligned mvg_vec1d_store_aligned
#define vec1d_store_unaligned mvg_vec1d_store_unaligned
#define vec1d_sub mvg_vec1d_sub
#define vec1d_zero mvg_vec1d_zero
#define vec1f mvg_vec1f
#define vec1f_add mvg_vec1f_add
#define vec1f_floor mvg_vec1f_floor
#define vec1f_fmadd mvg_vec1f_fmadd
#define vec1f_fnmadd mvg_vec1f_fnmadd
#define vec1f_load mvg_vec1f_load
#define vec1f_load_aligned mvg_vec1f_load_aligned
#define vec1f_load_unaligned mvg_vec1f_load_unaligned
#define vec1f_mul mvg_vec1f_mul
#define vec1f_set_f mvg_vec1f_set_f
#define vec1f_store mvg_vec1f_store
#define vec1f_store_aligned mvg_vec1f_store_aligned
#define vec1f_store_unaligned mvg_vec1f_store_unaligned
#define vec1f_sub mvg_vec1f_sub
#define vec1f_zero mvg_vec1f_zero
#define vec1n mvg_vec1n
#define vec1n_addmod mvg_vec1n_addmod
#define vec1n_convert_limited_vec1d mvg_vec1n_convert_limited_vec1d
#define vec1n_store_unaligned mvg_vec1n_store_unaligned
#define vec2d mvg_vec2d
#define vec2d_abs mvg_vec2d_abs
#define vec2d_add mvg_vec2d_add
#define vec2d_addsub mvg_vec2d_addsub
#define vec2d_blendv mvg_vec2d_blendv
#define vec2d_cmp_ge mvg_vec2d_cmp_ge
#define vec2d_cmp_gt mvg_vec2d_cmp_gt
#define vec2d_cmp_lt mvg_vec2d_cmp_lt
#define vec2d_convert_limited_vec2n mvg_vec2d_convert_limited_vec2n
#define vec2d_div mvg_vec2d_div
#define vec2d_floor mvg_vec2d_floor
#define vec2d_fmadd mvg_vec2d_fmadd
#define vec2d_fmsub mvg_vec2d_fmsub
#define vec2d_fnmadd mvg_vec2d_fnmadd
#define vec2d_fnmsub mvg_vec2d_fnmsub
#define vec2d_get_index mvg_vec2d_get_index
#define vec2d_half mvg_vec2d_half
#define vec2d_load mvg_vec2d_load
#define vec2d_load_aligned mvg_vec2d_load_aligned
#define vec2d_load_unaligned mvg_vec2d_load_unaligned
#define vec2d_max mvg_vec2d_max
#define vec2d_min mvg_vec2d_min
#define vec2d_mul mvg_vec2d_mul
#define vec2d_mulmod mvg_vec2d_mulmod
#define vec2d_neg mvg_vec2d_neg
#define vec2d_nmulmod mvg_vec2d_nmulmod
#define vec2d_one mvg_vec2d_one
#define vec2d_reduce_0n_to_pmhn mvg_vec2d_reduce_0n_to_pmhn
#define vec2d_reduce_2n_to_n mvg_vec2d_reduce_2n_to_n
#define vec2d_reduce_pm1n_to_pmhn mvg_vec2d_reduce_pm1n_to_pmhn
#define vec2d_reduce_pm1no_to_0n mvg_vec2d_reduce_pm1no_to_0n
#define vec2d_reduce_to_0n mvg_vec2d_reduce_to_0n
#define vec2d_reduce_to_pm1n mvg_vec2d_reduce_to_pm1n
#define vec2d_reduce_to_pm1no mvg_vec2d_reduce_to_pm1no
#define vec2d_round mvg_vec2d_round
#define vec2d_same mvg_vec2d_same
#define vec2d_same_mod mvg_vec2d_same_mod
#define vec2d_set_d mvg_vec2d_set_d
#define vec2d_set_d2 mvg_vec2d_set_d2
#define vec2d_store mvg_vec2d_store
#define vec2d_store_aligned mvg_vec2d_store_aligned
#define vec2d_store_unaligned mvg_vec2d_store_unaligned
#define vec2d_sub mvg_vec2d_sub
#define vec2d_unpackhi mvg_vec2d_unpackhi
#define vec2d_unpacklo mvg_vec2d_unpacklo
#define vec2d_zero mvg_vec2d_zero
#define vec2n mvg_vec2n
#define vec2n_add mvg_vec2n_add
#define vec2n_addmod mvg_vec2n_addmod
#define vec2n_addmod_limited mvg_vec2n_addmod_limited
#define vec2n_bit_and mvg_vec2n_bit_and
#define vec2n_bit_shift_right mvg_vec2n_bit_shift_right
#define vec2n_convert_limited_vec2d mvg_vec2n_convert_limited_vec2d
#define vec2n_horizontal_sum mvg_vec2n_horizontal_sum
#define vec2n_load_unaligned mvg_vec2n_load_unaligned
#define vec2n_mul mvg_vec2n_mul
#define vec2n_set_n mvg_vec2n_set_n
#define vec2n_store_unaligned mvg_vec2n_store_unaligned
#define vec2n_sub mvg_vec2n_sub
#define vec2n_zero mvg_vec2n_zero
#define vec4d mvg_vec4d
#define vec4d_abs mvg_vec4d_abs
#define vec4d_add mvg_vec4d_add
#define vec4d_addsub mvg_vec4d_addsub
#define vec4d_blendv mvg_vec4d_blendv
#define vec4d_cmp_ge mvg_vec4d_cmp_ge
#define vec4d_cmp_gt mvg_vec4d_cmp_gt
#define vec4d_cmp_lt mvg_vec4d_cmp_lt
#define vec4d_convert_limited_vec4n mvg_vec4d_convert_limited_vec4n
#define vec4d_div mvg_vec4d_div
#define vec4d_floor mvg_vec4d_floor
#define vec4d_fmadd mvg_vec4d_fmadd
#define vec4d_fmsub mvg_vec4d_fmsub
#define vec4d_fnmadd mvg_vec4d_fnmadd
#define vec4d_fnmsub mvg_vec4d_fnmsub
#define vec4d_get_index mvg_vec4d_get_index
#define vec4d_half mvg_vec4d_half
#define vec4d_load mvg_vec4d_load
#define vec4d_load_aligned mvg_vec4d_load_aligned
#define vec4d_load_unaligned mvg_vec4d_load_unaligned
#define vec4d_max mvg_vec4d_max
#define vec4d_min mvg_vec4d_min
#define vec4d_mul mvg_vec4d_mul
#define vec4d_mulmod mvg_vec4d_mulmod
#define vec4d_neg mvg_vec4d_neg
#define vec4d_nmulmod mvg_vec4d_nmulmod
#define vec4d_one mvg_vec4d_one
#define vec4d_permute2_0_2 mvg_vec4d_permute2_0_2
#define vec4d_permute2_1_3 mvg_vec4d_permute2_1_3
#define vec4d_permute_0_2_1_3 mvg_vec4d_permute_0_2_1_3
#define vec4d_permute_3_1_2_0 mvg_vec4d_permute_3_1_2_0
#define vec4d_permute_3_2_1_0 mvg_vec4d_permute_3_2_1_0
#define vec4d_print mvg_vec4d_print
#define vec4d_reduce_0n_to_pmhn mvg_vec4d_reduce_0n_to_pmhn
#define vec4d_reduce_2n_to_n mvg_vec4d_reduce_2n_to_n
#define vec4d_reduce_pm1n_to_pmhn mvg_vec4d_reduce_pm1n_to_pmhn
#define vec4d_reduce_pm1no_to_0n mvg_vec4d_reduce_pm1no_to_0n
#define vec4d_reduce_to_0n mvg_vec4d_reduce_to_0n
#define vec4d_reduce_to_pm1n mvg_vec4d_reduce_to_pm1n
#define vec4d_reduce_to_pm1no mvg_vec4d_reduce_to_pm1no
#define vec4d_round mvg_vec4d_round
#define vec4d_same mvg_vec4d_same
#define vec4d_same_mod mvg_vec4d_same_mod
#define vec4d_set_d mvg_vec4d_set_d
#define vec4d_set_d4 mvg_vec4d_set_d4
#define vec4d_set_vec2d2 mvg_vec4d_set_vec2d2
#define vec4d_store mvg_vec4d_store
#define vec4d_store_aligned mvg_vec4d_store_aligned
#define vec4d_store_unaligned mvg_vec4d_store_unaligned
#define vec4d_sub mvg_vec4d_sub
#define vec4d_unpack_hi_permute_0_2_1_3 mvg_vec4d_unpack_hi_permute_0_2_1_3
#define vec4d_unpack_lo_permute_0_2_1_3 mvg_vec4d_unpack_lo_permute_0_2_1_3
#define vec4d_unpackhi mvg_vec4d_unpackhi
#define vec4d_unpackhi_permute_3_1_2_0 mvg_vec4d_unpackhi_permute_3_1_2_0
#define vec4d_unpacklo mvg_vec4d_unpacklo
#define vec4d_unpacklo_permute_3_1_2_0 mvg_vec4d_unpacklo_permute_3_1_2_0
#define vec4d_zero mvg_vec4d_zero
#define vec4f mvg_vec4f
#define vec4f_add mvg_vec4f_add
#define vec4f_floor mvg_vec4f_floor
#define vec4f_fmadd mvg_vec4f_fmadd
#define vec4f_fnmadd mvg_vec4f_fnmadd
#define vec4f_load mvg_vec4f_load
#define vec4f_load_aligned mvg_vec4f_load_aligned
#define vec4f_load_unaligned mvg_vec4f_load_unaligned
#define vec4f_mul mvg_vec4f_mul
#define vec4f_set_f mvg_vec4f_set_f
#define vec4f_store mvg_vec4f_store
#define vec4f_store_aligned mvg_vec4f_store_aligned
#define vec4f_store_unaligned mvg_vec4f_store_unaligned
#define vec4f_sub mvg_vec4f_sub
#define vec4f_zero mvg_vec4f_zero
#define vec4n mvg_vec4n
#define vec4n_add mvg_vec4n_add
#define vec4n_addmod mvg_vec4n_addmod
#define vec4n_addmod_limited mvg_vec4n_addmod_limited
#define vec4n_bit_and mvg_vec4n_bit_and
#define vec4n_bit_shift_right mvg_vec4n_bit_shift_right
#define vec4n_convert_limited_vec4d mvg_vec4n_convert_limited_vec4d
#define vec4n_horizontal_sum mvg_vec4n_horizontal_sum
#define vec4n_load_unaligned mvg_vec4n_load_unaligned
#define vec4n_mul mvg_vec4n_mul
#define vec4n_permute_3_2_1_0 mvg_vec4n_permute_3_2_1_0
#define vec4n_print mvg_vec4n_print
#define vec4n_set_n mvg_vec4n_set_n
#define vec4n_set_n4 mvg_vec4n_set_n4
#define vec4n_store_unaligned mvg_vec4n_store_unaligned
#define vec4n_sub mvg_vec4n_sub
#define vec4n_zero mvg_vec4n_zero
#define vec8d mvg_vec8d
#define vec8d_abs mvg_vec8d_abs
#define vec8d_add mvg_vec8d_add
#define vec8d_blendv mvg_vec8d_blendv
#define vec8d_convert_limited_vec8n mvg_vec8d_convert_limited_vec8n
#define vec8d_div mvg_vec8d_div
#define vec8d_floor mvg_vec8d_floor
#define vec8d_fmadd mvg_vec8d_fmadd
#define vec8d_fmsub mvg_vec8d_fmsub
#define vec8d_fnmadd mvg_vec8d_fnmadd
#define vec8d_fnmsub mvg_vec8d_fnmsub
#define vec8d_get_index mvg_vec8d_get_index
#define vec8d_half mvg_vec8d_half
#define vec8d_load mvg_vec8d_load
#define vec8d_load_aligned mvg_vec8d_load_aligned
#define vec8d_load_unaligned mvg_vec8d_load_unaligned
#define vec8d_max mvg_vec8d_max
#define vec8d_min mvg_vec8d_min
#define vec8d_mul mvg_vec8d_mul
#define vec8d_mulmod mvg_vec8d_mulmod
#define vec8d_neg mvg_vec8d_neg
#define vec8d_nmulmod mvg_vec8d_nmulmod
#define vec8d_one mvg_vec8d_one
#define vec8d_reduce_0n_to_pmhn mvg_vec8d_reduce_0n_to_pmhn
#define vec8d_reduce_2n_to_n mvg_vec8d_reduce_2n_to_n
#define vec8d_reduce_pm1n_to_pmhn mvg_vec8d_reduce_pm1n_to_pmhn
#define vec8d_reduce_pm1no_to_0n mvg_vec8d_reduce_pm1no_to_0n
#define vec8d_reduce_to_0n mvg_vec8d_reduce_to_0n
#define vec8d_reduce_to_pm1n mvg_vec8d_reduce_to_pm1n
#define vec8d_reduce_to_pm1no mvg_vec8d_reduce_to_pm1no
#define vec8d_round mvg_vec8d_round
#define vec8d_same mvg_vec8d_same
#define vec8d_same_mod mvg_vec8d_same_mod
#define vec8d_set_d mvg_vec8d_set_d
#define vec8d_set_d8 mvg_vec8d_set_d8
#define vec8d_set_vec4d2 mvg_vec8d_set_vec4d2
#define vec8d_store mvg_vec8d_store
#define vec8d_store_aligned mvg_vec8d_store_aligned
#define vec8d_store_unaligned mvg_vec8d_store_unaligned
#define vec8d_sub mvg_vec8d_sub
#define vec8d_unpackhi mvg_vec8d_unpackhi
#define vec8d_unpacklo mvg_vec8d_unpacklo
#define vec8d_zero mvg_vec8d_zero
#define vec8f mvg_vec8f
#define vec8f_add mvg_vec8f_add
#define vec8f_floor mvg_vec8f_floor
#define vec8f_fmadd mvg_vec8f_fmadd
#define vec8f_fnmadd mvg_vec8f_fnmadd
#define vec8f_load mvg_vec8f_load
#define vec8f_load_aligned mvg_vec8f_load_aligned
#define vec8f_load_unaligned mvg_vec8f_load_unaligned
#define vec8f_mul mvg_vec8f_mul
#define vec8f_set_f mvg_vec8f_set_f
#define vec8f_store mvg_vec8f_store
#define vec8f_store_aligned mvg_vec8f_store_aligned
#define vec8f_store_unaligned mvg_vec8f_store_unaligned
#define vec8f_sub mvg_vec8f_sub
#define vec8f_zero mvg_vec8f_zero
#define vec8n mvg_vec8n
#define vec8n_add mvg_vec8n_add
#define vec8n_addmod mvg_vec8n_addmod
#define vec8n_addmod_limited mvg_vec8n_addmod_limited
#define vec8n_bit_and mvg_vec8n_bit_and
#define vec8n_bit_shift_right mvg_vec8n_bit_shift_right
#define vec8n_convert_limited_vec8d mvg_vec8n_convert_limited_vec8d
#define vec8n_horizontal_sum mvg_vec8n_horizontal_sum
#define vec8n_load_unaligned mvg_vec8n_load_unaligned
#define vec8n_mul mvg_vec8n_mul
#define vec8n_set_n mvg_vec8n_set_n
#define vec8n_store_unaligned mvg_vec8n_store_unaligned
#define vec8n_sub mvg_vec8n_sub
#define vec8n_zero mvg_vec8n_zero

#elif defined(FLINT_MV_RENAME_MVS)
#undef FLINT_MV_RENAME_MVS
#define _vec2d_i64 mvs__vec2d_i64
#define _vec2d_round_i64 mvs__vec2d_round_i64
#define _vec2i mvs__vec2i
#define _vec2n_small_i64_d mvs__vec2n_small_i64_d
#define _vec2u mvs__vec2u
#define _vec2d_fma mvs__vec2d_fma
#define _vec4d_fma mvs__vec4d_fma
#define _vec2d_signmask mvs__vec2d_signmask
#define _vec4d_signmask mvs__vec4d_signmask
#define _vec4d_i64 mvs__vec4d_i64
#define _vec4d_round_i64 mvs__vec4d_round_i64
#define _vec4i mvs__vec4i
#define _vec4n_small_i64_d mvs__vec4n_small_i64_d
#define _vec4u mvs__vec4u
#define _vec_generic_blendv1 mvs__vec_generic_blendv1
#define _vec_generic_i64_51_get_d mvs__vec_generic_i64_51_get_d
#define _vec_generic_mulmod1 mvs__vec_generic_mulmod1
#define _vec_generic_nmulmod1 mvs__vec_generic_nmulmod1
#define _vec_generic_reduce_pm1n_to_pmhn1 mvs__vec_generic_reduce_pm1n_to_pmhn1
#define _vec_generic_reduce_to_pm1n1 mvs__vec_generic_reduce_to_pm1n1
#define _vec_generic_round_i64_52 mvs__vec_generic_round_i64_52
#define vec16f mvs_vec16f
#define vec16f_add mvs_vec16f_add
#define vec16f_floor mvs_vec16f_floor
#define vec16f_fmadd mvs_vec16f_fmadd
#define vec16f_fnmadd mvs_vec16f_fnmadd
#define vec16f_load mvs_vec16f_load
#define vec16f_load_aligned mvs_vec16f_load_aligned
#define vec16f_load_unaligned mvs_vec16f_load_unaligned
#define vec16f_mul mvs_vec16f_mul
#define vec16f_set_f mvs_vec16f_set_f
#define vec16f_store mvs_vec16f_store
#define vec16f_store_aligned mvs_vec16f_store_aligned
#define vec16f_store_unaligned mvs_vec16f_store_unaligned
#define vec16f_sub mvs_vec16f_sub
#define vec16f_zero mvs_vec16f_zero
#define vec1d mvs_vec1d
#define vec1d_abs mvs_vec1d_abs
#define vec1d_add mvs_vec1d_add
#define vec1d_addsub mvs_vec1d_addsub
#define vec1d_blendv mvs_vec1d_blendv
#define vec1d_convert_limited_vec1n mvs_vec1d_convert_limited_vec1n
#define vec1d_div mvs_vec1d_div
#define vec1d_floor mvs_vec1d_floor
#define vec1d_fmadd mvs_vec1d_fmadd
#define vec1d_fmsub mvs_vec1d_fmsub
#define vec1d_fnmadd mvs_vec1d_fnmadd
#define vec1d_fnmsub mvs_vec1d_fnmsub
#define vec1d_half mvs_vec1d_half
#define vec1d_load mvs_vec1d_load
#define vec1d_load_aligned mvs_vec1d_load_aligned
#define vec1d_load_unaligned mvs_vec1d_load_unaligned
#define vec1d_max mvs_vec1d_max
#define vec1d_min mvs_vec1d_min
#define vec1d_mul mvs_vec1d_mul
#define vec1d_mulmod mvs_vec1d_mulmod
#define vec1d_neg mvs_vec1d_neg
#define vec1d_nmulmod mvs_vec1d_nmulmod
#define vec1d_one mvs_vec1d_one
#define vec1d_reduce_0n_to_pmhn mvs_vec1d_reduce_0n_to_pmhn
#define vec1d_reduce_2n_to_n mvs_vec1d_reduce_2n_to_n
#define vec1d_reduce_pm1n_to_pmhn mvs_vec1d_reduce_pm1n_to_pmhn
#define vec1d_reduce_pm1no_to_0n mvs_vec1d_reduce_pm1no_to_0n
#define vec1d_reduce_to_0n mvs_vec1d_reduce_to_0n
#define vec1d_reduce_to_pm1n mvs_vec1d_reduce_to_pm1n
#define vec1d_reduce_to_pm1no mvs_vec1d_reduce_to_pm1no
#define vec1d_round mvs_vec1d_round
#define vec1d_same mvs_vec1d_same
#define vec1d_same_mod mvs_vec1d_same_mod
#define vec1d_set_d mvs_vec1d_set_d
#define vec1d_store mvs_vec1d_store
#define vec1d_store_aligned mvs_vec1d_store_aligned
#define vec1d_store_unaligned mvs_vec1d_store_unaligned
#define vec1d_sub mvs_vec1d_sub
#define vec1d_zero mvs_vec1d_zero
#define vec1f mvs_vec1f
#define vec1f_add mvs_vec1f_add
#define vec1f_floor mvs_vec1f_floor
#define vec1f_fmadd mvs_vec1f_fmadd
#define vec1f_fnmadd mvs_vec1f_fnmadd
#define vec1f_load mvs_vec1f_load
#define vec1f_load_aligned mvs_vec1f_load_aligned
#define vec1f_load_unaligned mvs_vec1f_load_unaligned
#define vec1f_mul mvs_vec1f_mul
#define vec1f_set_f mvs_vec1f_set_f
#define vec1f_store mvs_vec1f_store
#define vec1f_store_aligned mvs_vec1f_store_aligned
#define vec1f_store_unaligned mvs_vec1f_store_unaligned
#define vec1f_sub mvs_vec1f_sub
#define vec1f_zero mvs_vec1f_zero
#define vec1n mvs_vec1n
#define vec1n_addmod mvs_vec1n_addmod
#define vec1n_convert_limited_vec1d mvs_vec1n_convert_limited_vec1d
#define vec1n_store_unaligned mvs_vec1n_store_unaligned
#define vec2d mvs_vec2d
#define vec2d_abs mvs_vec2d_abs
#define vec2d_add mvs_vec2d_add
#define vec2d_addsub mvs_vec2d_addsub
#define vec2d_blendv mvs_vec2d_blendv
#define vec2d_cmp_ge mvs_vec2d_cmp_ge
#define vec2d_cmp_gt mvs_vec2d_cmp_gt
#define vec2d_cmp_lt mvs_vec2d_cmp_lt
#define vec2d_convert_limited_vec2n mvs_vec2d_convert_limited_vec2n
#define vec2d_div mvs_vec2d_div
#define vec2d_floor mvs_vec2d_floor
#define vec2d_fmadd mvs_vec2d_fmadd
#define vec2d_fmsub mvs_vec2d_fmsub
#define vec2d_fnmadd mvs_vec2d_fnmadd
#define vec2d_fnmsub mvs_vec2d_fnmsub
#define vec2d_get_index mvs_vec2d_get_index
#define vec2d_half mvs_vec2d_half
#define vec2d_load mvs_vec2d_load
#define vec2d_load_aligned mvs_vec2d_load_aligned
#define vec2d_load_unaligned mvs_vec2d_load_unaligned
#define vec2d_max mvs_vec2d_max
#define vec2d_min mvs_vec2d_min
#define vec2d_mul mvs_vec2d_mul
#define vec2d_mulmod mvs_vec2d_mulmod
#define vec2d_neg mvs_vec2d_neg
#define vec2d_nmulmod mvs_vec2d_nmulmod
#define vec2d_one mvs_vec2d_one
#define vec2d_reduce_0n_to_pmhn mvs_vec2d_reduce_0n_to_pmhn
#define vec2d_reduce_2n_to_n mvs_vec2d_reduce_2n_to_n
#define vec2d_reduce_pm1n_to_pmhn mvs_vec2d_reduce_pm1n_to_pmhn
#define vec2d_reduce_pm1no_to_0n mvs_vec2d_reduce_pm1no_to_0n
#define vec2d_reduce_to_0n mvs_vec2d_reduce_to_0n
#define vec2d_reduce_to_pm1n mvs_vec2d_reduce_to_pm1n
#define vec2d_reduce_to_pm1no mvs_vec2d_reduce_to_pm1no
#define vec2d_round mvs_vec2d_round
#define vec2d_same mvs_vec2d_same
#define vec2d_same_mod mvs_vec2d_same_mod
#define vec2d_set_d mvs_vec2d_set_d
#define vec2d_set_d2 mvs_vec2d_set_d2
#define vec2d_store mvs_vec2d_store
#define vec2d_store_aligned mvs_vec2d_store_aligned
#define vec2d_store_unaligned mvs_vec2d_store_unaligned
#define vec2d_sub mvs_vec2d_sub
#define vec2d_unpackhi mvs_vec2d_unpackhi
#define vec2d_unpacklo mvs_vec2d_unpacklo
#define vec2d_zero mvs_vec2d_zero
#define vec2n mvs_vec2n
#define vec2n_add mvs_vec2n_add
#define vec2n_addmod mvs_vec2n_addmod
#define vec2n_addmod_limited mvs_vec2n_addmod_limited
#define vec2n_bit_and mvs_vec2n_bit_and
#define vec2n_bit_shift_right mvs_vec2n_bit_shift_right
#define vec2n_convert_limited_vec2d mvs_vec2n_convert_limited_vec2d
#define vec2n_horizontal_sum mvs_vec2n_horizontal_sum
#define vec2n_load_unaligned mvs_vec2n_load_unaligned
#define vec2n_mul mvs_vec2n_mul
#define vec2n_set_n mvs_vec2n_set_n
#define vec2n_store_unaligned mvs_vec2n_store_unaligned
#define vec2n_sub mvs_vec2n_sub
#define vec2n_zero mvs_vec2n_zero
#define vec4d mvs_vec4d
#define vec4d_abs mvs_vec4d_abs
#define vec4d_add mvs_vec4d_add
#define vec4d_addsub mvs_vec4d_addsub
#define vec4d_blendv mvs_vec4d_blendv
#define vec4d_cmp_ge mvs_vec4d_cmp_ge
#define vec4d_cmp_gt mvs_vec4d_cmp_gt
#define vec4d_cmp_lt mvs_vec4d_cmp_lt
#define vec4d_convert_limited_vec4n mvs_vec4d_convert_limited_vec4n
#define vec4d_div mvs_vec4d_div
#define vec4d_floor mvs_vec4d_floor
#define vec4d_fmadd mvs_vec4d_fmadd
#define vec4d_fmsub mvs_vec4d_fmsub
#define vec4d_fnmadd mvs_vec4d_fnmadd
#define vec4d_fnmsub mvs_vec4d_fnmsub
#define vec4d_get_index mvs_vec4d_get_index
#define vec4d_half mvs_vec4d_half
#define vec4d_load mvs_vec4d_load
#define vec4d_load_aligned mvs_vec4d_load_aligned
#define vec4d_load_unaligned mvs_vec4d_load_unaligned
#define vec4d_max mvs_vec4d_max
#define vec4d_min mvs_vec4d_min
#define vec4d_mul mvs_vec4d_mul
#define vec4d_mulmod mvs_vec4d_mulmod
#define vec4d_neg mvs_vec4d_neg
#define vec4d_nmulmod mvs_vec4d_nmulmod
#define vec4d_one mvs_vec4d_one
#define vec4d_permute2_0_2 mvs_vec4d_permute2_0_2
#define vec4d_permute2_1_3 mvs_vec4d_permute2_1_3
#define vec4d_permute_0_2_1_3 mvs_vec4d_permute_0_2_1_3
#define vec4d_permute_3_1_2_0 mvs_vec4d_permute_3_1_2_0
#define vec4d_permute_3_2_1_0 mvs_vec4d_permute_3_2_1_0
#define vec4d_print mvs_vec4d_print
#define vec4d_reduce_0n_to_pmhn mvs_vec4d_reduce_0n_to_pmhn
#define vec4d_reduce_2n_to_n mvs_vec4d_reduce_2n_to_n
#define vec4d_reduce_pm1n_to_pmhn mvs_vec4d_reduce_pm1n_to_pmhn
#define vec4d_reduce_pm1no_to_0n mvs_vec4d_reduce_pm1no_to_0n
#define vec4d_reduce_to_0n mvs_vec4d_reduce_to_0n
#define vec4d_reduce_to_pm1n mvs_vec4d_reduce_to_pm1n
#define vec4d_reduce_to_pm1no mvs_vec4d_reduce_to_pm1no
#define vec4d_round mvs_vec4d_round
#define vec4d_same mvs_vec4d_same
#define vec4d_same_mod mvs_vec4d_same_mod
#define vec4d_set_d mvs_vec4d_set_d
#define vec4d_set_d4 mvs_vec4d_set_d4
#define vec4d_set_vec2d2 mvs_vec4d_set_vec2d2
#define vec4d_store mvs_vec4d_store
#define vec4d_store_aligned mvs_vec4d_store_aligned
#define vec4d_store_unaligned mvs_vec4d_store_unaligned
#define vec4d_sub mvs_vec4d_sub
#define vec4d_unpack_hi_permute_0_2_1_3 mvs_vec4d_unpack_hi_permute_0_2_1_3
#define vec4d_unpack_lo_permute_0_2_1_3 mvs_vec4d_unpack_lo_permute_0_2_1_3
#define vec4d_unpackhi mvs_vec4d_unpackhi
#define vec4d_unpackhi_permute_3_1_2_0 mvs_vec4d_unpackhi_permute_3_1_2_0
#define vec4d_unpacklo mvs_vec4d_unpacklo
#define vec4d_unpacklo_permute_3_1_2_0 mvs_vec4d_unpacklo_permute_3_1_2_0
#define vec4d_zero mvs_vec4d_zero
#define vec4f mvs_vec4f
#define vec4f_add mvs_vec4f_add
#define vec4f_floor mvs_vec4f_floor
#define vec4f_fmadd mvs_vec4f_fmadd
#define vec4f_fnmadd mvs_vec4f_fnmadd
#define vec4f_load mvs_vec4f_load
#define vec4f_load_aligned mvs_vec4f_load_aligned
#define vec4f_load_unaligned mvs_vec4f_load_unaligned
#define vec4f_mul mvs_vec4f_mul
#define vec4f_set_f mvs_vec4f_set_f
#define vec4f_store mvs_vec4f_store
#define vec4f_store_aligned mvs_vec4f_store_aligned
#define vec4f_store_unaligned mvs_vec4f_store_unaligned
#define vec4f_sub mvs_vec4f_sub
#define vec4f_zero mvs_vec4f_zero
#define vec4n mvs_vec4n
#define vec4n_add mvs_vec4n_add
#define vec4n_addmod mvs_vec4n_addmod
#define vec4n_addmod_limited mvs_vec4n_addmod_limited
#define vec4n_bit_and mvs_vec4n_bit_and
#define vec4n_bit_shift_right mvs_vec4n_bit_shift_right
#define vec4n_convert_limited_vec4d mvs_vec4n_convert_limited_vec4d
#define vec4n_horizontal_sum mvs_vec4n_horizontal_sum
#define vec4n_load_unaligned mvs_vec4n_load_unaligned
#define vec4n_mul mvs_vec4n_mul
#define vec4n_permute_3_2_1_0 mvs_vec4n_permute_3_2_1_0
#define vec4n_print mvs_vec4n_print
#define vec4n_set_n mvs_vec4n_set_n
#define vec4n_set_n4 mvs_vec4n_set_n4
#define vec4n_store_unaligned mvs_vec4n_store_unaligned
#define vec4n_sub mvs_vec4n_sub
#define vec4n_zero mvs_vec4n_zero
#define vec8d mvs_vec8d
#define vec8d_abs mvs_vec8d_abs
#define vec8d_add mvs_vec8d_add
#define vec8d_blendv mvs_vec8d_blendv
#define vec8d_convert_limited_vec8n mvs_vec8d_convert_limited_vec8n
#define vec8d_div mvs_vec8d_div
#define vec8d_floor mvs_vec8d_floor
#define vec8d_fmadd mvs_vec8d_fmadd
#define vec8d_fmsub mvs_vec8d_fmsub
#define vec8d_fnmadd mvs_vec8d_fnmadd
#define vec8d_fnmsub mvs_vec8d_fnmsub
#define vec8d_get_index mvs_vec8d_get_index
#define vec8d_half mvs_vec8d_half
#define vec8d_load mvs_vec8d_load
#define vec8d_load_aligned mvs_vec8d_load_aligned
#define vec8d_load_unaligned mvs_vec8d_load_unaligned
#define vec8d_max mvs_vec8d_max
#define vec8d_min mvs_vec8d_min
#define vec8d_mul mvs_vec8d_mul
#define vec8d_mulmod mvs_vec8d_mulmod
#define vec8d_neg mvs_vec8d_neg
#define vec8d_nmulmod mvs_vec8d_nmulmod
#define vec8d_one mvs_vec8d_one
#define vec8d_reduce_0n_to_pmhn mvs_vec8d_reduce_0n_to_pmhn
#define vec8d_reduce_2n_to_n mvs_vec8d_reduce_2n_to_n
#define vec8d_reduce_pm1n_to_pmhn mvs_vec8d_reduce_pm1n_to_pmhn
#define vec8d_reduce_pm1no_to_0n mvs_vec8d_reduce_pm1no_to_0n
#define vec8d_reduce_to_0n mvs_vec8d_reduce_to_0n
#define vec8d_reduce_to_pm1n mvs_vec8d_reduce_to_pm1n
#define vec8d_reduce_to_pm1no mvs_vec8d_reduce_to_pm1no
#define vec8d_round mvs_vec8d_round
#define vec8d_same mvs_vec8d_same
#define vec8d_same_mod mvs_vec8d_same_mod
#define vec8d_set_d mvs_vec8d_set_d
#define vec8d_set_d8 mvs_vec8d_set_d8
#define vec8d_set_vec4d2 mvs_vec8d_set_vec4d2
#define vec8d_store mvs_vec8d_store
#define vec8d_store_aligned mvs_vec8d_store_aligned
#define vec8d_store_unaligned mvs_vec8d_store_unaligned
#define vec8d_sub mvs_vec8d_sub
#define vec8d_unpackhi mvs_vec8d_unpackhi
#define vec8d_unpacklo mvs_vec8d_unpacklo
#define vec8d_zero mvs_vec8d_zero
#define vec8f mvs_vec8f
#define vec8f_add mvs_vec8f_add
#define vec8f_floor mvs_vec8f_floor
#define vec8f_fmadd mvs_vec8f_fmadd
#define vec8f_fnmadd mvs_vec8f_fnmadd
#define vec8f_load mvs_vec8f_load
#define vec8f_load_aligned mvs_vec8f_load_aligned
#define vec8f_load_unaligned mvs_vec8f_load_unaligned
#define vec8f_mul mvs_vec8f_mul
#define vec8f_set_f mvs_vec8f_set_f
#define vec8f_store mvs_vec8f_store
#define vec8f_store_aligned mvs_vec8f_store_aligned
#define vec8f_store_unaligned mvs_vec8f_store_unaligned
#define vec8f_sub mvs_vec8f_sub
#define vec8f_zero mvs_vec8f_zero
#define vec8n mvs_vec8n
#define vec8n_add mvs_vec8n_add
#define vec8n_addmod mvs_vec8n_addmod
#define vec8n_addmod_limited mvs_vec8n_addmod_limited
#define vec8n_bit_and mvs_vec8n_bit_and
#define vec8n_bit_shift_right mvs_vec8n_bit_shift_right
#define vec8n_convert_limited_vec8d mvs_vec8n_convert_limited_vec8d
#define vec8n_horizontal_sum mvs_vec8n_horizontal_sum
#define vec8n_load_unaligned mvs_vec8n_load_unaligned
#define vec8n_mul mvs_vec8n_mul
#define vec8n_set_n mvs_vec8n_set_n
#define vec8n_store_unaligned mvs_vec8n_store_unaligned
#define vec8n_sub mvs_vec8n_sub
#define vec8n_zero mvs_vec8n_zero

#elif defined(FLINT_MV_RENAME_UNDEF)
#undef FLINT_MV_RENAME_UNDEF
#undef _vec2d_i64
#undef _vec2d_round_i64
#undef _vec2i
#undef _vec2n_small_i64_d
#undef _vec2u
#undef _vec2d_fma
#undef _vec4d_fma
#undef _vec2d_signmask
#undef _vec4d_signmask
#undef _vec4d_i64
#undef _vec4d_round_i64
#undef _vec4i
#undef _vec4n_small_i64_d
#undef _vec4u
#undef _vec_generic_blendv1
#undef _vec_generic_i64_51_get_d
#undef _vec_generic_mulmod1
#undef _vec_generic_nmulmod1
#undef _vec_generic_reduce_pm1n_to_pmhn1
#undef _vec_generic_reduce_to_pm1n1
#undef _vec_generic_round_i64_52
#undef vec16f
#undef vec16f_add
#undef vec16f_floor
#undef vec16f_fmadd
#undef vec16f_fnmadd
#undef vec16f_load
#undef vec16f_load_aligned
#undef vec16f_load_unaligned
#undef vec16f_mul
#undef vec16f_set_f
#undef vec16f_store
#undef vec16f_store_aligned
#undef vec16f_store_unaligned
#undef vec16f_sub
#undef vec16f_zero
#undef vec1d
#undef vec1d_abs
#undef vec1d_add
#undef vec1d_addsub
#undef vec1d_blendv
#undef vec1d_convert_limited_vec1n
#undef vec1d_div
#undef vec1d_floor
#undef vec1d_fmadd
#undef vec1d_fmsub
#undef vec1d_fnmadd
#undef vec1d_fnmsub
#undef vec1d_half
#undef vec1d_load
#undef vec1d_load_aligned
#undef vec1d_load_unaligned
#undef vec1d_max
#undef vec1d_min
#undef vec1d_mul
#undef vec1d_mulmod
#undef vec1d_neg
#undef vec1d_nmulmod
#undef vec1d_one
#undef vec1d_reduce_0n_to_pmhn
#undef vec1d_reduce_2n_to_n
#undef vec1d_reduce_pm1n_to_pmhn
#undef vec1d_reduce_pm1no_to_0n
#undef vec1d_reduce_to_0n
#undef vec1d_reduce_to_pm1n
#undef vec1d_reduce_to_pm1no
#undef vec1d_round
#undef vec1d_same
#undef vec1d_same_mod
#undef vec1d_set_d
#undef vec1d_store
#undef vec1d_store_aligned
#undef vec1d_store_unaligned
#undef vec1d_sub
#undef vec1d_zero
#undef vec1f
#undef vec1f_add
#undef vec1f_floor
#undef vec1f_fmadd
#undef vec1f_fnmadd
#undef vec1f_load
#undef vec1f_load_aligned
#undef vec1f_load_unaligned
#undef vec1f_mul
#undef vec1f_set_f
#undef vec1f_store
#undef vec1f_store_aligned
#undef vec1f_store_unaligned
#undef vec1f_sub
#undef vec1f_zero
#undef vec1n
#undef vec1n_addmod
#undef vec1n_convert_limited_vec1d
#undef vec1n_store_unaligned
#undef vec2d
#undef vec2d_abs
#undef vec2d_add
#undef vec2d_addsub
#undef vec2d_blendv
#undef vec2d_cmp_ge
#undef vec2d_cmp_gt
#undef vec2d_cmp_lt
#undef vec2d_convert_limited_vec2n
#undef vec2d_div
#undef vec2d_floor
#undef vec2d_fmadd
#undef vec2d_fmsub
#undef vec2d_fnmadd
#undef vec2d_fnmsub
#undef vec2d_get_index
#undef vec2d_half
#undef vec2d_load
#undef vec2d_load_aligned
#undef vec2d_load_unaligned
#undef vec2d_max
#undef vec2d_min
#undef vec2d_mul
#undef vec2d_mulmod
#undef vec2d_neg
#undef vec2d_nmulmod
#undef vec2d_one
#undef vec2d_reduce_0n_to_pmhn
#undef vec2d_reduce_2n_to_n
#undef vec2d_reduce_pm1n_to_pmhn
#undef vec2d_reduce_pm1no_to_0n
#undef vec2d_reduce_to_0n
#undef vec2d_reduce_to_pm1n
#undef vec2d_reduce_to_pm1no
#undef vec2d_round
#undef vec2d_same
#undef vec2d_same_mod
#undef vec2d_set_d
#undef vec2d_set_d2
#undef vec2d_store
#undef vec2d_store_aligned
#undef vec2d_store_unaligned
#undef vec2d_sub
#undef vec2d_unpackhi
#undef vec2d_unpacklo
#undef vec2d_zero
#undef vec2n
#undef vec2n_add
#undef vec2n_addmod
#undef vec2n_addmod_limited
#undef vec2n_bit_and
#undef vec2n_bit_shift_right
#undef vec2n_convert_limited_vec2d
#undef vec2n_horizontal_sum
#undef vec2n_load_unaligned
#undef vec2n_mul
#undef vec2n_set_n
#undef vec2n_store_unaligned
#undef vec2n_sub
#undef vec2n_zero
#undef vec4d
#undef vec4d_abs
#undef vec4d_add
#undef vec4d_addsub
#undef vec4d_blendv
#undef vec4d_cmp_ge
#undef vec4d_cmp_gt
#undef vec4d_cmp_lt
#undef vec4d_convert_limited_vec4n
#undef vec4d_div
#undef vec4d_floor
#undef vec4d_fmadd
#undef vec4d_fmsub
#undef vec4d_fnmadd
#undef vec4d_fnmsub
#undef vec4d_get_index
#undef vec4d_half
#undef vec4d_load
#undef vec4d_load_aligned
#undef vec4d_load_unaligned
#undef vec4d_max
#undef vec4d_min
#undef vec4d_mul
#undef vec4d_mulmod
#undef vec4d_neg
#undef vec4d_nmulmod
#undef vec4d_one
#undef vec4d_permute2_0_2
#undef vec4d_permute2_1_3
#undef vec4d_permute_0_2_1_3
#undef vec4d_permute_3_1_2_0
#undef vec4d_permute_3_2_1_0
#undef vec4d_print
#undef vec4d_reduce_0n_to_pmhn
#undef vec4d_reduce_2n_to_n
#undef vec4d_reduce_pm1n_to_pmhn
#undef vec4d_reduce_pm1no_to_0n
#undef vec4d_reduce_to_0n
#undef vec4d_reduce_to_pm1n
#undef vec4d_reduce_to_pm1no
#undef vec4d_round
#undef vec4d_same
#undef vec4d_same_mod
#undef vec4d_set_d
#undef vec4d_set_d4
#undef vec4d_set_vec2d2
#undef vec4d_store
#undef vec4d_store_aligned
#undef vec4d_store_unaligned
#undef vec4d_sub
#undef vec4d_unpack_hi_permute_0_2_1_3
#undef vec4d_unpack_lo_permute_0_2_1_3
#undef vec4d_unpackhi
#undef vec4d_unpackhi_permute_3_1_2_0
#undef vec4d_unpacklo
#undef vec4d_unpacklo_permute_3_1_2_0
#undef vec4d_zero
#undef vec4f
#undef vec4f_add
#undef vec4f_floor
#undef vec4f_fmadd
#undef vec4f_fnmadd
#undef vec4f_load
#undef vec4f_load_aligned
#undef vec4f_load_unaligned
#undef vec4f_mul
#undef vec4f_set_f
#undef vec4f_store
#undef vec4f_store_aligned
#undef vec4f_store_unaligned
#undef vec4f_sub
#undef vec4f_zero
#undef vec4n
#undef vec4n_add
#undef vec4n_addmod
#undef vec4n_addmod_limited
#undef vec4n_bit_and
#undef vec4n_bit_shift_right
#undef vec4n_convert_limited_vec4d
#undef vec4n_horizontal_sum
#undef vec4n_load_unaligned
#undef vec4n_mul
#undef vec4n_permute_3_2_1_0
#undef vec4n_print
#undef vec4n_set_n
#undef vec4n_set_n4
#undef vec4n_store_unaligned
#undef vec4n_sub
#undef vec4n_zero
#undef vec8d
#undef vec8d_abs
#undef vec8d_add
#undef vec8d_blendv
#undef vec8d_convert_limited_vec8n
#undef vec8d_div
#undef vec8d_floor
#undef vec8d_fmadd
#undef vec8d_fmsub
#undef vec8d_fnmadd
#undef vec8d_fnmsub
#undef vec8d_get_index
#undef vec8d_half
#undef vec8d_load
#undef vec8d_load_aligned
#undef vec8d_load_unaligned
#undef vec8d_max
#undef vec8d_min
#undef vec8d_mul
#undef vec8d_mulmod
#undef vec8d_neg
#undef vec8d_nmulmod
#undef vec8d_one
#undef vec8d_reduce_0n_to_pmhn
#undef vec8d_reduce_2n_to_n
#undef vec8d_reduce_pm1n_to_pmhn
#undef vec8d_reduce_pm1no_to_0n
#undef vec8d_reduce_to_0n
#undef vec8d_reduce_to_pm1n
#undef vec8d_reduce_to_pm1no
#undef vec8d_round
#undef vec8d_same
#undef vec8d_same_mod
#undef vec8d_set_d
#undef vec8d_set_d8
#undef vec8d_set_vec4d2
#undef vec8d_store
#undef vec8d_store_aligned
#undef vec8d_store_unaligned
#undef vec8d_sub
#undef vec8d_unpackhi
#undef vec8d_unpacklo
#undef vec8d_zero
#undef vec8f
#undef vec8f_add
#undef vec8f_floor
#undef vec8f_fmadd
#undef vec8f_fnmadd
#undef vec8f_load
#undef vec8f_load_aligned
#undef vec8f_load_unaligned
#undef vec8f_mul
#undef vec8f_set_f
#undef vec8f_store
#undef vec8f_store_aligned
#undef vec8f_store_unaligned
#undef vec8f_sub
#undef vec8f_zero
#undef vec8n
#undef vec8n_add
#undef vec8n_addmod
#undef vec8n_addmod_limited
#undef vec8n_bit_and
#undef vec8n_bit_shift_right
#undef vec8n_convert_limited_vec8d
#undef vec8n_horizontal_sum
#undef vec8n_load_unaligned
#undef vec8n_mul
#undef vec8n_set_n
#undef vec8n_store_unaligned
#undef vec8n_sub
#undef vec8n_zero

#else
# error force_generic_renames.h needs a FLINT_MV_RENAME_* selector
#endif
